name: Feature request
description: Proponer una mejora o nueva funcionalidad
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema a resolver
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Propuesta técnica
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impacto esperado en gameplay/compatibilidad
    validations:
      required: false
